export const projects = [
    {
      title: 'Weather-Widget',
      breif: 'A website providing weather information using an external API.',
      description: `
        <p>I developed a dynamic weather application using React to provide users with real-time weather information. The application allows users to input a city name and fetches current weather data through the OpenWeatherMap API. This project demonstrates my ability to build interactive, data-driven web applications with live API integrations</p>
        <p>The user interface is designed for ease of use, featuring a simple input field where users can type in the city name. Upon submission, the application queries the OpenWeatherMap API and displays weather details such as temperature, humidity, and weather conditions. This ensures that users receive up-to-date and relevant weather information instantly</p>
        <p>The application highlights my skills in React and API handling, showcasing how I can create responsive and efficient web solutions. By integrating the OpenWeatherMap API</p>
      `,
      link: 'https://github.com/apsarunnisa-shaik/weather-widget',
      techStack: ['React', 'OpenWeatherMap API', 'JavaScript'],
    },

    {
      title: 'Stay Finder',
      breif: 'A full-featured rental platform similar to Airbnb',
      description: `
        <p>The "Stay Finder" project is a comprehensive rental platform designed to offer functionalities similar to Airbnb. It allows users to search for available properties based on their criteria and location, view detailed listings, and allowes to add a property.</p>
        <p>The application features user-friendly interfaces for both property owners and property viewers. Property owners can list their properties, delete and update as well, while renters can browse listings, read reviews, add a review, sand view location.</p>
        <p>This project demonstrates the ability to create a robust and scalable rental solution, integrating features such as user authentication, authorisation, and interactive maps. The platform emphasizes usability, performance, and a seamless user experience.</p>`,
      link: 'https://github.com/apsarunnisa-shaik/rentalPlatform',
      techStack: ['Node.js', 'Express.js', 'MongoDB', 'Mongo Atla', 'Render'],
    },
    {
        title: 'Simon-Say Game',
        breif: 'An interactive memory game that tests pattern recognition.',
        description: `
        <p>The Simon-Say Game is a classic memory challenge designed to enhance pattern recognition skills. Players must replicate a sequence of colors or sounds generated by the game, with each round adding complexity.</p>
        <p>The game features a user-friendly interface with vibrant colors, creating an engaging experience for players of all ages. It tests player's memory.</p>
        <p>This project showcases proficiency in HTML, CSS, and JavaScript, demonstrating how to create interactive and visually appealing web applications. It highlights the ability to develop logic-driven games with responsive design elements.</p>
        `,
        link: 'https://github.com/apsarunnisa-shaik/Simon-Say-Game',
        techStack: ['HTML', 'CSS', 'JavaScript'],
    },
    
    {
        title: 'Rock-Paper-Scissor',
        breif: 'A classic hand game played against the computer.',
        description: `
        <p>The Rock-Paper-Scissors game is a classic hand game played against the computer. Players choose one of three options: rock, paper, or scissors, and the computer makes a choice as well. The winner is determined based on the rules: rock beats scissors, scissors beat paper, and paper beats rock.</p>
        <p>The game features a simple and intuitive interface, allowing players to easily select their choice and view the outcome of each round. It tracks score and number of games played in a session to enhance the interactive experience.</p>
        <p>This project demonstrates skills in HTML, CSS, and JavaScript by creating a functional and visually appealing game. It highlights the ability to implement game logic and user interactions in a web application.</p>
        `,
        link: 'https://github.com/apsarunnisa-shaik/Rock-Paper-Scissor',
        techStack: ['HTML', 'CSS', 'JavaScript'],
    },
      
    {
        title: 'Tic-Tak-Toe Game',
        breif:'A strategy-based game where two players alternate marking spaces in a grid. The goal is to be the first to get three in a row',
        description: `
        <p>The Tic-Tac-Toe game is a classic strategy-based game played on a 3x3 grid. Two players take turns marking spaces with their respective symbols—X and O. The objective is to be the first to align three symbols in a row, either horizontally, vertically, or diagonally.</p>
        <p>The game features a user-friendly interface where players can easily place their marks and see the game board update in real-time. It includes functionality to check for win conditions, ties, and restart the game.</p>
        <p>This project showcases proficiency in HTML, CSS, and JavaScript by implementing game logic, user interaction, and dynamic updates. It highlights the ability to create engaging and interactive web applications.</p>
        `,
        link: 'https://github.com/apsarunnisa-shaik/Tic-Tak-Toe',
        techStack: ['HTML', 'CSS', 'JavaScript'],
    },
      
    {
        title: 'Spotify-Clone',
        breif: 'A music streaming platform where users can search, play, and manage their favorite songs. Designed to mimic the experience of Spotify.',
        description: `
        <p>The Spotify-Clone project is a music streaming platform designed to replicate the Spotify UX. The project includes a multi-page layout with navigation, closely mirroring Spotify's user interface</p>
        <p>By using advanced CSS techniques and responsive design principles, the project effectively simulates the look and feel of Spotify.</p>
        <p>This project demonstrates skills in HTML and CSS by creating a responsive and visually appealing layout. The design incorporates key elements of Spotify's interface, including navigation, and playlist management</p>
        
        `,
        link: 'https://github.com/apsarunnisa-shaik/Spotify-Clone',
        techStack: ['HTML', 'CSS'],
    }
      
  ];
  